### ISSUE TITLE
Review TP2

### ISSUE THREAD

**Issue by clementserrano** [PolytechLyon/isi3-tp2-visiteur-serrano-piard-tp2#1]
Bonjour M. Caron,

Que pensez-vous du code + rapport ?
Je me suis permis de passer l'interface Noeud en classe abstract, cela ne pose pas de problèmes ?

Merci de votre retour.

**Comment by Slashgear** [comment]
- Qu'est ce que c'est pas jolie les instance of comme ça ! 😨 Expliquer moi en quoi c'est mal ?
https://github.com/PolytechLyon/isi3-tp2-visiteur-serrano-piard-tp2/blob/ca02cb6038370251c00bccdd9060f836aa3821d3/src/main/java/visiteur/VisiteurInfixe.java#L11

Rappelez moi le but du pattern Visiteur ?

On pourrait gérer cette priorité autrement, comme un aspect du Node ? 

- le rapport est cool 👍

**Comment by clementserrano** [comment]
**instance of** est mal car cela complique l'extension de l'application. Il faudra modifier le visiteur pour implémenter les nouvelles opérations.

Le but de Visiteur est de définir de nouvelles opérations **sans changer** les classes des éléments qu'on visite.

J'ai décidé de gérer les priorités directement dans le père et de remplacer le nœud père stocké par une valeur de priorité.

https://github.com/PolytechLyon/isi3-tp2-visiteur-serrano-piard-tp2/blob/54f479e281251f8884925c64b61830feeaf0415f/src/main/java/visiteur/VisiteurInfixe.java#L17

**Comment by Slashgear** [comment]
Alors ça me va, mais petit conseil, donne un nom à tes priorités. Pourquoi pas passer par un Enum valué.

Ainsi la personne qui arrive sur ton code pourra plus facilement comprendre ce que signifie une priorité de 1 😄 

Tu comprends l'intérêt ?

**Comment by clementserrano** [comment]
Bonjour,

Oui effectivement je me suis posé la question si les valeurs 0 et 1 n'étaient pas trop vagues.
J'ai donc ajouté un Enum Priorite avec deux valeurs Faible et Forte.
Cela donne de la signification et facilite l'extension (nouvelles priorités). 

https://github.com/PolytechLyon/isi3-tp2-visiteur-serrano-piard-tp2/blob/master/src/main/java/expression/Priorite.java
